server:
  port: 8901
logging:
  level:
    root: INFO
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.100.35:8080/auth/realms/plutus/protocol/openid-connect/certs